name: CI

on: [push, pull_request]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install poetry chuy
          poetry install
      - name: Run pylint
        run: chuy lint
      - name: Run Pytest
        run: chuy tests
