name: Pylint

on: [push, pull_request]

jobs:
  luacheck:          
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update      
          pip install poetry
          poetry install
      - name: Run pylint
        run: poetry run pytest
